language: go

go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - tip

install:
  - go get -d -t github.com/opentracing/opentracing-go/...
  - go get -u github.com/golang/dep/cmd/dep
script:
  - make deps test lint
  - go build ./...
